name: 95504_Helper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "1 16 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上0点1分自动执行

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
        run: npm ci && node 95504/index.js "${USER}" "${PASS}"
