name: Hifini_Helper

on:
  schedule:
    - cron: "1 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build

  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: |
          npm ci
          npm run build
          node dist/hifini/index.js "${USER}" "${PASS}" "${TO}" "${HIFINI_COOKIE}"
        env:
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
          HIFINI_COOKIE: ${{ secrets.HIFINI_COOKIE }} 