name: Hifini_Helper

on:
  schedule:
    - cron: "1 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: corepack enable
      - run: corepack install
      - run: pnpm i
      - run: pnpm run build

  send:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: build project
        run: |
          corepack enable
          corepack install
          pnpm i
          pnpm run build
      - name: run script
        run: node dist/hifini/index.js "${USER}" "${PASS}" "${TO}" "${HIFINI_COOKIE}" "${HIFINI_DOMAIN}"
        env:
          USER: ${{ secrets.USER }} # for email auth
          PASS: ${{ secrets.PASS }} # for email auth
          TO: ${{ secrets.TO }}
          HIFINI_DOMAIN: ${{ secrets.HIFINI_DOMAIN }} 
          HIFINI_COOKIE: ${{ secrets.HIFINI_COOKIE }} 