name: JueJin_Helper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "1 16 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天早上0点1分自动执行

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: npm ci

  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          COOKIE: ${{ secrets.COOKIE }}
          COOKIE1: ${{ secrets.COOKIE1 }}
          COOKIE2: ${{ secrets.COOKIE2 }}
          COOKIE3: ${{ secrets.COOKIE3 }}
          COOKIE4: ${{ secrets.COOKIE4 }}
          COOKIE5: ${{ secrets.COOKIE5 }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
        run: npm ci && node juejin/index.js "${USER}" "${PASS}" "${TO}" "${COOKIE}" "${COOKIE1}" "${COOKIE2}" "${COOKIE3}" "${COOKIE4}" "${COOKIE5}"
